### ISSUE TITLE
Where is the "user-files"

### ISSUE THREAD

**Issue by sentriz** [zaggash/docker-filerun#5]
Hello, I thought I would try this container because the official one does [this](https://github.com/filerun/docker/blob/master/entrypoint.sh#L9)

Which breaks /user-files (where my media is mounted into the container), so I'm checking this container out (which seems to do linuxservers PGID/PUID stuff?) - so it looks good

My question is, what volume should I set for my media (the "/user-files") when the official container's volumes are "/var/www/html", and "/user-files".

Thank you

**Comment by zaggash** [comment]
Hello,

by default it is setup to /config/www/filerun/system/data

But you can definitly add a docker volume -v /my/folder/data:/data
and change in filerun your user data to /data

Control Panel -> Users -> Edit User -> Permissions -> Home Folder.

Hope it helps.

didn't tested it since I'm not using it anymore.
I have to rework this container in my todo list.

**Comment by sentriz** [comment]
ahhhh
I didn't know the path could be changed via the GUI. Great

Well say I used `-v /my/folder/data:/data` then changed my home folder to "/data" in the GUI. 
Would you filerun container then change the permissions of the contents of the volume? or if it would, would it use PGID/PUID? and what about new files?

Thank you very much

**Comment by zaggash** [comment]
No, at the moment the container do not care about these files, it doesn't change the permission at runtime.
I didn't test it again but I think new files should be set to the UID of the abc user which run php/nginx.

So you would likely want to use PGID/PUID.

**Comment by zaggash** [comment]
--- Reopen if you need more digging.
